// LocalExplorer Weather Sayings Database
// This file contains all weather phrases, categorized by style, condition, and theme.

// Theme flair emojis, moved from appState for co-location
export const themeFlairs = {
	'naval': '⚓',
	'sunset': '🌅',
	'neon': '✨',
	'arctic': '🏔️',
	'highseas': '🌊',
	'aurora': '🌌',
	'arcane': '🔮',
	'solstice': '☀️',
	'evergreen': '🌲',
	'voyager': '🚀',
	'monochrome': '⬛',
	'playful': '🎨',
	'retro90': '📼',
	'groove70': '🕺',
	'mojave': '🌵',
	'atomic50': '⚛️',
	'psychedelic60': '☮️',
	'arcade80': '👾',
	'y2k00': '💿',
	'metro10': '📱',
	'sushi': '🍣',
	'bbq': '🍖',
	'cafe': '☕'
};

export const weatherSayings = {
  // ====================================================================
  // REGULAR PHRASES (Polite & Encouraging)
  // ====================================================================
  regular: {
    // General sayings for each weather condition
    conditions: {
      sunny: [
        "Beautiful clear skies today!",
        "Perfect weather for outdoor activities",
        "Great day to get outside",
        "Lovely clear conditions",
        "Wonderful day ahead",
        "Perfect weather for exploring",
        "Great time to enjoy nature",
        "Clear and beautiful outside",
        "Perfect day for adventures",
        "Wonderful weather conditions",
        "Great conditions for outdoor fun",
        "Clear skies mean great opportunities",
        "Perfect time for outdoor activities",
        "Beautiful day to be outside",
        "Great weather for activities",
        "Wonderful clear day",
        "Perfect for being outdoors",
        "Clear and lovely",
        "Great day for outdoor enjoyment",
        "Lovely clear weather",
        "Perfect for outdoor times",
        "Beautiful conditions outside",
        "Wonderful clear conditions",
        "Great for being outside",
        "Ideal clear day",
        "Perfect clear weather",
        "Clear and pleasant vibes",
        "Great for outdoor activities",
        "Lovely clear conditions",
        "Perfect for outdoor fun",
        "Beautiful clear day",
        "Wonderful clear weather",
        "Great clear day ahead",
        "Ideal for outdoor activities",
        "Perfect beautiful skies",
        "Clear but pleasant",
        "Great clear conditions",
        "Lovely clear day",
        "Perfect for outdoor adventures",
        "Beautiful clear weather",
        "Wonderful clear day",
        "Great for outdoor comfort",
        "Ideal clear weather",
        "Perfect day for clear skies",
        "Clear and peaceful",
        "Great day for being out",
        "Lovely clear day",
        "Perfect clear conditions",
        "Beautiful clear weather",
        "Wonderful clear day ahead",
        "Great for outdoor time",
        "Ideal clear day",
        "Perfect for being outside",
        "Clear refreshing air",
        "Great clear day",
        "Lovely clear weather",
        "Perfect clear day",
        "Beautiful clear conditions",
        "Wonderful clear conditions",
        "Great clear weather",
        "Ideal for outdoor fun",
        "Perfect beautiful day",
        "Clear and lovely",
        "Great clear weather",
        "Lovely clear day ahead",
        "Perfect clear day ahead",
        "Beautiful clear weather",
        "Wonderful clear weather",
        "Great for clear skies",
        "Ideal clear conditions",
        "Perfect for outdoor activities",
        "Clear bright day",
        "Great beautiful weather",
        "Lovely clear conditions",
        "Perfect clear weather",
        "Beautiful clear conditions",
        "Wonderful clear weather",
        "Great clear conditions",
        "Ideal clear day ahead",
        "Perfect for outdoor enjoyment",
        "Clear pleasant weather",
        "Great day for clear skies",
        "Lovely clear weather",
        "Perfect clear conditions",
        "Beautiful clear day",
        "Wonderful clear weather ahead",
        "Great for clear conditions",
        "Ideal clear weather",
        "Perfect clear day",
        "Clear and nice",
        "Great clear day",
        "Lovely clear day ahead",
        "Perfect for outdoor clear activities",
        "Beautiful clear weather",
        "Wonderful clear weather",
        "Great clear conditions",
        "Ideal for outdoor clarity",
        "Perfect clear beautiful day",
        "Clear wonderful weather",
        "Beautiful sunny day! Perfect for outdoor activities",
        "Warm weather ahead - stay hydrated and enjoy!",
        "Great day to visit the beach or pool",
        "Lovely warm temperatures today",
        "Perfect weather for a picnic in the park",
        "Wonderful sunny conditions - don't forget sunscreen!",
        "Ideal day for outdoor dining",
        "Gorgeous warm day ahead",
        "Perfect time to enjoy outdoor activities",
        "Beautiful weather for a nature walk",
        "Great day to explore your city",
        "Warm and pleasant - perfect for being outside",
        "Lovely conditions for outdoor recreation",
        "Beautiful day to spend time in nature",
        "Perfect weather for garden activities",
        "Wonderful day for outdoor sports",
        "Great conditions for hiking",
        "Ideal weather for a bike ride",
        "Beautiful day for outdoor photography",
        "Perfect time to enjoy local parks",
        "Warm and inviting weather today",
        "Great day for outdoor exercise",
        "Lovely weather for a stroll",
        "Perfect conditions for outdoor dining",
        "Beautiful day to explore outdoors",
        "Wonderful weather for activities",
        "Great time to be outside",
        "Ideal for outdoor adventures",
        "Perfect day for sunshine",
        "Warm and delightful weather",
        "Beautiful conditions outside",
        "Great weather for fun",
        "Lovely day ahead",
        "Perfect for outdoor plans",
        "Wonderful sunny conditions",
        "Great day to enjoy nature",
        "Ideal weather for exploration",
        "Beautiful warm day",
        "Perfect for being active",
        "Warm and wonderful weather",
        "Great conditions today",
        "Lovely outdoor weather",
        "Perfect day for adventures",
        "Beautiful and warm",
        "Wonderful day ahead",
        "Great weather conditions",
        "Ideal for outdoor fun",
        "Perfect sunny day",
        "Warm and pleasant",
        "Beautiful day to enjoy",
        "Great time outside",
        "Lovely warm weather",
        "Perfect conditions",
        "Wonderful day",
        "Great weather",
        "Ideal day",
        "Beautiful conditions",
        "Perfect weather",
        "Warm and nice",
        "Great day",
        "Lovely weather",
        "Perfect time",
        "Beautiful day",
        "Wonderful weather",
        "Great conditions",
        "Ideal weather",
        "Perfect for activities",
        "Warm weather",
        "Beautiful outside",
        "Great outdoor weather",
        "Lovely conditions",
        "Perfect day ahead",
        "Wonderful conditions",
        "Great sunny day",
        "Ideal for outdoor activities",
        "Beautiful weather today",
        "Perfect for exploring",
        "Warm and sunny",
        "Great day to be out",
        "Lovely day for activities",
        "Perfect outdoor weather",
        "Beautiful warm conditions",
        "Wonderful sunny weather",
        "Great day for sunshine",
        "Ideal warm weather",
        "Perfect pleasant day",
        "Warm and beautiful",
        "Great weather for fun",
        "Lovely outdoor day",
        "Perfect for being outside",
        "Beautiful day for activities",
        "Wonderful warm weather",
        "Great conditions for fun",
        "Ideal sunny day",
        "Perfect day to explore",
        "Warm inviting weather",
        "Beautiful day outside",
        "Great weather ahead",
        "Lovely sunny conditions",
        "Perfect warm day",
        "Wonderful outdoor weather"
      ],
      partlySunny: [
        "A nice mix of sun and clouds today.",
        "Perfectly pleasant weather. Enjoy!",
        "The clouds are just giving the sun a little break.",
        "A great day to be outside, not too bright.",
        "Looks like a comfortable day for a walk.",
        "Sun's playing peek-a-boo!",
        "Not too hot, not too bright. Just right.",
        "Looks like a beautiful, mild day.",
        "A perfectly comfortable day to be out and about.",
        "The best of both worlds: sun and shade!",
        "You'll get a little sun, a little shade. Perfect.",
        "Lovely day with some picturesque clouds.",
        "A very pleasant day ahead.",
        "Great weather for a stroll.",
        "It's a 'partly perfect' day."
      ],
      cloudy: [
        "A bit overcast, but still a great day to explore.",
        "No need for sunglasses today!",
        "Even light, perfect for taking photos.",
        "A cozy, cloudy day. Good for a quiet walk.",
        "The sky is a soft grey blanket today.",
        "A bit gloomy, but the air is fresh.",
        "The clouds are out, but it's still a good day.",
        "Looks like a calm, cool day.",
        "A good day for indoor plans or a moody walk.",
        "The sun is taking a day off. You don't have to.",
        "It's a bit gray, but don't let it get you down.",
        "A pensive, cloudy day.",
        "Good weather for a museum or a cozy cafe.",
        "The definition of 'meh' weather, but you can make it great!",
        "Bundle up and stay warm today!",
        "Perfect weather for cozy indoor activities",
        "Great day for hot chocolate and warm drinks",
        "Chilly conditions - dress in layers",
        "Wonderful day for comfort food",
        "Perfect weather for staying cozy",
        "Great time for indoor hobbies",
        "Cold but beautiful outside",
        "Perfect day for warm beverages",
        "Wonderful weather for reading indoors",
        "Cold weather calls for warm clothes",
        "Perfect time for indoor relaxation",
        "Beautiful crisp day ahead",
        "Wonderful cold day",
        "Perfect for bundling up",
        "Cold but refreshing",
        "Great day for warmth",
        "Lovely winter weather",
        "Perfect for cozy times",
        "Beautiful chilly day",
        "Wonderful cold conditions",
        "Great for staying warm",
        "Ideal winter day",
        "Perfect cold weather",
        "Cold and clear outside",
        "Great for winter fun",
        "Lovely chilly conditions",
        "Perfect for warmth",
        "Beautiful winter day",
        "Wonderful chilly weather",
        "Great cold day ahead",
        "Ideal for layers",
        "Perfect crisp weather",
        "Cold but pleasant",
        "Great winter conditions",
        "Lovely cold day",
        "Perfect for warm clothes",
        "Beautiful chilly weather",
        "Wonderful winter conditions",
        "Great for staying cozy",
        "Ideal cold day",
        "Perfect winter weather",
        "Cold and beautiful",
        "Great day for warmth",
        "Lovely winter day",
        "Perfect chilly conditions",
        "Beautiful cold weather",
        "Wonderful crisp day",
        "Great for bundling",
        "Ideal winter weather",
        "Perfect for staying warm",
        "Cold refreshing air",
        "Great chilly day",
        "Lovely cold weather",
        "Perfect winter day",
        "Beautiful cold conditions",
        "Wonderful chilly day",
        "Great cold weather",
        "Ideal for warm drinks",
        "Perfect crisp day",
        "Cold but lovely",
        "Great winter weather",
        "Lovely chilly day",
        "Perfect cold day",
        "Beautiful winter weather",
        "Wonderful cold day",
        "Great for winter",
        "Ideal chilly conditions",
        "Perfect for cozy",
        "Cold clear day",
        "Great crisp weather",
        "Lovely winter conditions",
        "Perfect cold conditions",
        "Beautiful chilly conditions",
        "Wonderful winter weather",
        "Great cold conditions",
        "Ideal winter day ahead",
        "Perfect for winter activities",
        "Cold invigorating weather",
        "Great day for layers",
        "Lovely cold conditions",
        "Perfect winter conditions",
        "Beautiful cold day",
        "Wonderful chilly weather ahead",
        "Great for staying inside",
        "Ideal cold weather",
        "Perfect chilly day",
        "Cold but nice",
        "Great winter day",
        "Lovely cold day ahead",
        "Perfect for warm cozy activities",
        "Beautiful crisp weather",
        "Wonderful cold weather",
        "Great chilly conditions",
        "Ideal for winter fun",
        "Perfect cold crisp day",
        "Cold beautiful weather"
      ],
      rain: [
        "Don't forget your umbrella today!",
        "Perfect weather for indoor activities",
        "Great day for staying cozy inside",
        "Rain expected - plan accordingly",
        "Wonderful day for indoor hobbies",
        "Perfect weather for reading",
        "Great time for movies and relaxation",
        "Rainy but peaceful outside",
        "Perfect day for comfort activities",
        "Wonderful weather for staying in",
        "Great conditions for indoor fun",
        "Rain brings growth and renewal",
        "Perfect time for indoor projects",
        "Beautiful rainy day ahead",
        "Great weather for cozy activities",
        "Wonderful rainy conditions",
        "Perfect for staying dry",
        "Rainy but calming",
        "Great day for indoor comfort",
        "Lovely rainy weather",
        "Perfect for cozy times",
        "Beautiful rain outside",
        "Wonderful wet conditions",
        "Great for staying inside",
        "Ideal rainy day",
        "Perfect rainy weather",
        "Rain and peaceful vibes",
        "Great for indoor relaxation",
        "Lovely wet conditions",
        "Perfect for staying cozy",
        "Beautiful rainy day",
        "Wonderful rain weather",
        "Great wet day ahead",
        "Ideal for indoor activities",
        "Perfect calming rain",
        "Rainy but pleasant",
        "Great rainy conditions",
        "Lovely rain day",
        "Perfect for staying warm and dry",
        "Beautiful wet weather",
        "Wonderful rainy day",
        "Great for indoor comfort",
        "Ideal rainy weather",
        "Perfect day for rain",
        "Rainy and peaceful",
        "Great day for staying in",
        "Lovely rainy day",
        "Perfect wet conditions",
        "Beautiful rain weather",
        "Wonderful wet day",
        "Great for indoor time",
        "Ideal rain weather",
        "Perfect for staying inside",
        "Rainy refreshing air",
        "Great wet day",
        "Lovely rain weather",
        "Perfect rainy day",
        "Beautiful wet conditions",
        "Wonderful rain day",
        "Great rainy weather",
        "Ideal for indoor fun",
        "Perfect calming day",
        "Rainy but lovely",
        "Great rain weather",
        "Lovely wet day",
        "Perfect rain day",
        "Beautiful rainy weather",
        "Wonderful wet weather",
        "Great for rain",
        "Ideal wet conditions",
        "Perfect for cozy indoors",
        "Rainy clear day",
        "Great calming weather",
        "Lovely rainy conditions",
        "Perfect wet weather",
        "Beautiful rain conditions",
        "Wonderful rainy weather",
        "Great wet conditions",
        "Ideal rainy day ahead",
        "Perfect for indoor relaxation",
        "Rainy peaceful weather",
        "Great day for umbrellas",
        "Lovely wet conditions",
        "Perfect rainy conditions",
        "Beautiful wet day",
        "Wonderful rain weather ahead",
        "Great for staying dry",
        "Ideal wet weather",
        "Perfect rain day ahead",
        "Rainy but nice",
        "Great rainy day",
        "Lovely rain day ahead",
        "Perfect for indoor cozy activities",
        "Beautiful calming weather",
        "Wonderful wet weather ahead",
        "Great rain conditions",
        "Ideal for indoor comfort",
        "Perfect wet calming day",
        "Rainy beautiful weather"
      ],
      thunderstorm: [
        "Storms expected! Best to stay indoors.",
        "Looks like a powerful storm is rolling in. Stay safe!",
        "A good day to watch the lightning from a safe distance.",
        "The weather is looking dramatic today!",
        "Definitely not a day for a walk in the park.",
        "Cozy up inside, it's going to be loud!",
        "Nature is putting on a show today. Watch from the window.",
        "Be careful, thunderstorms are in the forecast.",
        "A good day for a movie marathon inside.",
        "Stay safe and dry!",
        "Weather update: loud and flashy.",
        "Remember to unplug sensitive electronics!",
        "A classic 'thunderstorm' kind of day.",
        "Keep an eye on the sky, it's going to be an active day."
      ],
      snow: [
        "Winter wonderland today!",
        "Perfect weather for winter activities",
        "Great day for snow fun",
        "Snowy conditions - drive carefully",
        "Wonderful winter day",
        "Perfect weather for snow activities",
        "Great time for winter sports",
        "Snowy but beautiful outside",
        "Perfect day for winter fun",
        "Wonderful snowy weather",
        "Great conditions for winter enjoyment",
        "Snow brings winter magic",
        "Perfect time for snow activities",
        "Beautiful snowy day ahead",
        "Great weather for winter",
        "Wonderful snow conditions",
        "Perfect for winter activities",
        "Snowy and lovely",
        "Great day for snow",
        "Lovely snowy weather",
        "Perfect for winter times",
        "Beautiful snow outside",
        "Wonderful winter conditions",
        "Great for winter fun",
        "Ideal snowy day",
        "Perfect snowy weather",
        "Snow and peaceful vibes",
        "Great for winter activities",
        "Lovely winter conditions",
        "Perfect for winter fun",
        "Beautiful snowy day",
        "Wonderful snow weather",
        "Great snowy day ahead",
        "Ideal for winter activities",
        "Perfect winter snow",
        "Snowy but pleasant",
        "Great snowy conditions",
        "Lovely snow day",
        "Perfect for winter adventures",
        "Beautiful winter weather",
        "Wonderful snowy day",
        "Great for winter comfort",
        "Ideal snowy weather",
        "Perfect day for snow",
        "Snowy and peaceful",
        "Great day for winter",
        "Lovely snowy day",
        "Perfect snow conditions",
        "Beautiful snow weather",
        "Wonderful winter day",
        "Great for winter time",
        "Ideal snow weather",
        "Perfect for winter",
        "Snowy refreshing air",
        "Great snowy day",
        "Lovely snow weather",
        "Perfect snowy day",
        "Beautiful winter conditions",
        "Wonderful snow day",
        "Great snowy weather",
        "Ideal for winter fun",
        "Perfect winter day",
        "Snowy and lovely",
        "Great snow weather",
        "Lovely winter day",
        "Perfect snow day",
        "Beautiful snowy weather",
        "Wonderful winter weather",
        "Great for snow",
        "Ideal winter conditions",
        "Perfect for winter activities",
        "Snowy bright day",
        "Great winter weather",
        "Lovely snowy conditions",
        "Perfect winter weather",
        "Beautiful snow conditions",
        "Wonderful snowy weather",
        "Great winter conditions",
        "Ideal snowy day ahead",
        "Perfect for winter enjoyment",
        "Snowy peaceful weather",
        "Great day for snow activities",
        "Lovely winter weather",
        "Perfect snowy conditions",
        "Beautiful winter day",
        "Wonderful snow weather ahead",
        "Great for winter",
        "Ideal winter weather",
        "Perfect snowy day ahead",
        "Snowy and nice",
        "Great winter day",
        "Lovely snowy day ahead",
        "Perfect for winter cozy activities",
        "Beautiful winter weather",
        "Wonderful snowy weather",
        "Great snow conditions",
        "Ideal for winter activities",
        "Perfect snowy beautiful day",
        "Snowy wonderful weather"
      ],
      general: [
        "Have a great day!",
        "Enjoy the weather today",
        "Perfect day ahead",
        "Lovely conditions outside",
        "Wonderful day",
        "Great weather for your plans",
        "Beautiful day ahead",
        "Perfect conditions today",
        "Wonderful weather ahead",
        "Great day to be alive",
        "Lovely day ahead",
        "Perfect weather conditions",
        "Beautiful weather today",
        "Great conditions outside",
        "Wonderful day ahead",
        "Perfect day for activities",
        "Lovely weather today",
        "Great day ahead",
        "Beautiful conditions",
        "Wonderful weather",
        "Perfect for your day",
        "Lovely day",
        "Great weather",
        "Beautiful day",
        "Wonderful conditions",
        "Perfect weather",
        "Lovely conditions",
        "Great day",
        "Beautiful weather",
        "Wonderful day",
        "Perfect day",
        "Lovely weather",
        "Great conditions",
        "Beautiful day",
        "Wonderful weather",
        "Perfect conditions",
        "Lovely day ahead",
        "Great weather ahead",
        "Beautiful conditions ahead",
        "Wonderful day ahead",
        "Perfect day ahead",
        "Lovely weather ahead",
        "Great conditions ahead",
        "Beautiful weather ahead",
        "Wonderful conditions ahead",
        "Perfect weather ahead",
        "Enjoy your day",
        "Have a wonderful day",
        "Great day to be out",
        "Perfect day for fun",
        "Lovely day for activities"
      ]
    },
    // Theme-specific REGULAR phrases
    themes: {
      naval: {
        sunny: ["Clear skies and a calm sea. A perfect day to be on the water."],
        cloudy: ["A bit overcast, but good for spotting lighthouses."],
        rain: ["Batten down the hatches, looks like a squall's brewing."],
        thunderstorm: ["All hands on deck! This is a real storm."],
        general: ["A fine day for a sailor."]
      },
      sunset: {
        sunny: ["This weather is as beautiful as a sunset cruise."],
        partlySunny: ["The clouds might make for an even better sunset!"],
        cloudy: ["Looks like the sunset will be hidden tonight."],
        rain: ["A bit too wet to watch the sun go down. Stay warm!"],
        general: ["Wishing you a beautiful evening."]
      },
      neon: {
        sunny: ["The city lights will look amazing tonight."],
        cloudy: ["This fog is giving real cyberpunk vibes."],
        rain: ["This rain is making all the neon lights reflect. Kind of cool?"],
        thunderstorm: ["The city's electric, and so is the sky!"],
        general: ["A great day for the city."]
      },
      arctic: {
        sunny: ["Crisp and clear, just like an arctic morning."],
        partlySunny: ["A little cloud cover can't hurt."],
        cloudy: ["A classic grey arctic day. Stay warm."],
        snow: ["It's snowing. Again. A good day for the cabin."],
        general: ["Stay warm out there."]
      },
      highseas: {
        sunny: ["Calm seas and fair winds. A perfect day."],
        cloudy: ["The fog is rolling in. Very mysterious."],
        rain: ["Looks like a squall is brewing. Be careful."],
        thunderstorm: ["Rough seas today. Best to stay in port."],
        general: ["May your sails be full."]
      },
      aurora: {
        sunny: ["Clear day! Let's hope for clear skies tonight, too!"],
        cloudy: ["Too cloudy to see any lights tonight."],
        general: ["Hoping for a magical night."],
      },
      arcane: {
        sunny: ["A magical day, full of possibilities."],
        rain: ["The weather is mysterious today..."],
        thunderstorm: ["The sky is full of energy! A powerful day."],
        general: ["An enchanting day to you."]
      },
      solstice: {
        sunny: ["The sun is shining bright! Enjoy the long day."],
        cloudy: ["Even the sun needs a rest. A cloudy day."],
        general: ["Wishing you a bright day."]
      },
      evergreen: {
        sunny: ["Perfect day for a hike in the trails."],
        cloudy: ["The forest is misty and quiet today."],
        rain: ["The forest smells amazing in the rain."],
        general: ["Enjoy the forest."]
      },
      voyager: {
        sunny: ["Clear skies, perfect for stargazing later."],
        partlySunny: ["A few clouds... mostly harmless."],
        thunderstorm: ["Atmospheric disturbance detected. Seek shelter."],
        general: ["A great day to explore new frontiers."]
      },
      monochrome: {
        sunny: ["A clear, simple, beautiful day."],
        cloudy: ["It's a grey, overcast day. Very monochrome."],
        rain: ["Rain streaks add texture to the grey."],
        general: ["A day of contrasts."]
      },
      playful: {
        sunny: ["What a fun, happy day! Go play!"],
        rain: ["Rain, rain, go away. Time to play inside!"],
        general: ["Have a fun day!"]
      },
      retro90: {
        sunny: ["This weather is all that and a bag of chips. Go outside!"],
        cloudy: ["A bit gloomy. Bummer, man."],
        rain: ["This rain is wack. Stay inside."],
        general: ["Have a radical day."]
      },
      groove70: {
        sunny: ["Solid gold weather. Can you dig it?"],
        cloudy: ["A bit of a bummer, but stay groovy."],
        rain: ["This rain is a drag, man."],
        general: ["Far out!"]
      },
      mojave: {
        sunny: ["It's a beautiful, dry heat.", "Clear skies over the dunes."],
        cloudy: ["A rare cloudy day in the desert."],
        rain: ["A desert rainstorm! A rare sight."],
        general: ["Stay hydrated out there."]
      },
      atomic50: {
        sunny: ["What a swell day! Perfect for a picnic."],
        cloudy: ["Gee, it's a bit gray out."],
        rain: ["Heavens to Betsy, it's raining cats and dogs."],
        general: ["Have a peachy keen day!"]
      },
      psychedelic60: {
        sunny: ["What a far-out, beautiful day!"],
        cloudy: ["The clouds are, like, a total vibe, man."],
        rain: ["This rain is a total downer."],
        general: ["Peace, love, and good weather."]
      },
      arcade80: {
        sunny: ["Totally awesome weather! Go for a high score."],
        partlySunny: ["The weather is, like, pretty choice."],
        rain: ["Gag me with a spoon! This rain is bogus."],
        general: ["Have a tubular day."]
      },
      y2k00: {
        sunny: ["This weather is off the hook!"],
        rain: ["This rain is so not cool."],
        cloudy: ["Lame. This weather is wack."],
        general: ["Have a sweet day."]
      },
      metro10: {
        sunny: ["Weather looks good. Let's get this bread."],
        cloudy: ["This weather is not the vibe."],
        rain: ["It's raining. I can't even."],
        general: ["It is what it is."]
      },
      sushi: {
        sunny: ["A crisp, clean, perfect day."],
        cloudy: ["A calm, overcast day. Very balanced."],
        rain: ["A bit wet. Good day for some warm sake."],
        general: ["Enjoy a day of harmony."]
      },
      bbq: {
        sunny: [
          "Weather is so nice, let's get the grill out!",
          "Perfect day for some low and slow smoking.",
          "Sunshine and grill marks, that's what it's all about.",
          "Not a cloud in the sky. Fire up the pit!",
          "It's a beautiful day to be outside with some barbecue.",
          "Smells like grilling weather to me.",
          "This is a 10/10 day for a backyard BBQ.",
          "Get the charcoal, it's a perfect day.",
          "You couldn't ask for better weather to grill.",
          "The sun's out! Time to get the smoker going."
        ],
        partlySunny: [
          "A little cloud cover won't stop this grill.",
          "Sun's playing peek-a-boo. Grill's staying on.",
          "Perfectly pleasant. Get those skewers ready."
        ],
        cloudy: [
          "Who needs the sun when you have the glow of the charcoal?",
          "An overcast day is a perfect day to tend the smoker.",
          "It's not raining, so we're grilling."
        ],
        rain: [
          "Rain can't stop a true pitmaster. To the garage!",
          "A little rain just adds moisture. Keep grilling.",
          "Looks like it's an indoor 'grilling' (oven) day.",
          "A little drizzle won't hurt. We're still grilling.",
          "This weather is terrible. Good thing the smoker has a lid."
        ],
        thunderstorm: [
          "Okay, even I'm not grilling in lightning. Stay inside.",
          "The sky is rumbling. Better pause the cook."
        ],
        snow: [
          "Cold weather just means the fire feels even better.",
          "Snowing? Perfect excuse to try smoking that brisket.",
          "It's cold, but that's what the grill's heat is for."
        ],
        general: [
          "Every day is a good day to grill.",
          "Weather's looking good for a feast."
        ]
      },
      cafe: {
        sunny: ["Perfect weather for an iced coffee on the patio."],
        partlySunny: ["A great day for a latte and a quiet walk."],
        cloudy: ["The perfect gloomy weather to sit in a cafe and read."],
        rain: ["Cozy rainy day. Perfect for a warm cup of coffee."],
        general: ["Time for a coffee break."]
      }
    }
  },
  // ====================================================================
  // SASSY PHRASES (Blunt & Humorous)
  // ====================================================================
  sassy: {
    // General sayings for each weather condition
    conditions: {
      sunny: [
        "Damn, look at that beautiful sky, get your ass outside",
        "Perfect day to touch some grass and pretend you're productive",
        "It's gorgeous out, stop doom-scrolling and go outside",
        "Weather's so nice, even your excuses won't work today",
        "Get out there before Mother Nature changes her mind",
        "This is your sign to go outside and pretend to be active",
        "Perfect day to avoid responsibilities in the sunshine",
        "It's so nice out, even introverts are considering leaving",
        "Weather brought to you by 'no excuses to stay inside'",
        "Today's forecast: Too nice to waste on your couch",
        "The universe is basically begging you to go outside",
        "It's gorgeous, stop making excuses and get some vitamin D",
        "Perfect weather for pretending you have your life together",
        "This is what dreams are made of, now get out there",
        "Weather so nice, even your plants are judging you for staying in",
        "Today's the day to actually use that gym membership... or not",
        "It's beautiful out, time to disappoint your couch",
        "Perfect conditions for outdoor procrastination",
        "This weather is too good to waste on being inside",
        "Get outside before the weather gods change their minds",
        "It's so nice, even your excuses are weak today",
        "Today's brought to you by perfect weather and good vibes",
        "Weather's telling you to stop being a hermit",
        "Perfect day to touch grass and feel feelings",
        "It's gorgeous, your couch will survive without you",
        "This is your intervention from the weather gods",
        "Too nice to spend scrolling through existential dread",
        "Weather forecast: No excuses, get outside",
        "It's beautiful, time to pretend you're outdoorsy",
        "Perfect day for Instagram photos and fake productivity",
        "This weather is basically screaming 'go outside dummy'",
        "Too gorgeous to waste on indoor depression",
        "Today's vibe: Outdoorsy with scattered good choices",
        "The weather gods have blessed us, don't waste it",
        "It's so nice, even homebodies are reconsidering",
        "Perfect conditions for pretending you exercise",
        "This is what weather is supposed to be like, enjoy it",
        "Too beautiful to spend on your phone",
        "Weather brought to you by sunshine and possibilities",
        "It's gorgeous out, your couch can wait",
        "Perfect day to make poor decisions outdoors instead of indoors",
        "This weather is too good for your usual bullshit excuses",
        "Get outside before climate change ruins this too",
        "It's so nice, even vampires are considering going out",
        "Today's forecast: Beautiful with scattered good decisions",
        "Weather's perfect, time to actually leave the house",
        "This is your sign from the universe to go outside",
        "Too nice to waste on existential dread indoors",
        "Perfect weather for outdoor mediocrity",
        "It's gorgeous, stop being a shut-in",
        "Weather so good, you'll regret staying inside",
        "Today's brought to you by sunshine and good vibes only",
        "This is what peak weather performance looks like",
        "Perfect day to pretend you're an outdoors person",
        "It's beautiful, your responsibilities can wait",
        "Weather forecast: Absolutely stunning, no excuses",
        "Too nice to spend indoors being sad",
        "This weather is a gift, don't fuck it up",
        "Perfect conditions for touching grass and living life",
        "It's so gorgeous, even your phone is judging you",
        "Today's vibe: Sunshine with scattered motivation",
        "The weather gods are basically peer pressuring you to go out",
        "Too beautiful to waste on your couch potato lifestyle",
        "Perfect day for outdoor adventures or outdoor naps, your choice",
        "This weather is what Instagram was made for",
        "It's gorgeous out, time to be the main character",
        "Weather brought to you by 'stop making excuses'",
        "Too nice to spend on indoor existential crises",
        "Perfect day to pretend you have your shit together",
        "This is peak weather, enjoy it before it's gone",
        "It's beautiful, your anxiety can take a day off",
        "Weather forecast: Stunning with zero excuses accepted",
        "Too gorgeous to waste being a hermit",
        "Perfect conditions for making memories or mistakes",
        "This weather is what happens when the universe cooperates",
        "It's so nice, even pessimists are smiling",
        "Today's brought to you by perfect weather and no regrets",
        "Weather's amazing, time to actually live a little",
        "Too beautiful to spend doom-scrolling",
        "Perfect day for outdoor shenanigans",
        "This is your sign to stop procrastinating and go outside",
        "It's gorgeous, make the most of it",
        "Weather forecast: Perfection with scattered adventures",
        "Too nice for your usual indoor depression",
        "Perfect weather for pretending you're photogenic",
        "This is what happens when Mother Nature shows off",
        "It's beautiful out, time to be a functional human",
        "Weather brought to you by good vibes and sunshine",
        "Too gorgeous to waste on Netflix binges",
        "Perfect day for touching grass and feeling alive",
        "This weather is basically perfect, don't mess it up",
        "It's so nice, even your excuses sound pathetic",
        "Today's vibe: Outdoorsy with zero clouds",
        "The weather is literally perfect, get out there",
        "Too beautiful to spend on your couch",
        "Perfect conditions for living your best life or faking it",
        "This is peak weather performance, appreciate it",
        "It's gorgeous, time to pretend you're athletic",
        "Weather forecast: Absolutely beautiful, go outside now",
        "Bruh, take your lazy ass for a walk it's a nice day",
        "It's hotter than the devil's asshole out there",
        "Last time it was this hot, I got kicked out of Chili's for getting naked and eating fajitas - the fucking sizzzzle man",
        "Holy hell, did someone forget to turn off the surface of the sun?",
        "It's so hot, I just saw a squirrel using oven mitts to hold nuts",
        "Satan called, he wants his thermostat back",
        "This heat is more aggressive than my mother-in-law at Thanksgiving",
        "Seriously? More hot? We get it, climate change is real",
        "I'm not saying it's hot, but I just saw two fire hydrants fighting over a dog",
        "This weather is sponsored by Hell: Now in HD",
        "Perfect weather for spontaneous combustion",
        "It's so hot, even my shadow's looking for shade",
        "This is hotter than a jalapeño's armpit",
        "Weather forecast: Satan's breath with a chance of regret",
        "If it gets any hotter, we're all gonna be medium rare",
        "This heat is more extra than a Kardashian photo shoot",
        "It's like walking through a dragon's sneeze out there",
        "Hot enough to make a polar bear question their life choices",
        "This is what happens when Mother Nature goes through menopause",
        "I'd complain about the heat, but my vocal cords melted",
        "Today's forecast: Molten lava with scattered feelings of doom",
        "It's so hot, I just witnessed a chicken laying a hard-boiled egg",
        "Satan's using this day as his vacation spot",
        "This heat is more intense than my anxiety on a Monday",
        "Someone left the gates of Hell open again",
        "It's like being slow-roasted by an angry god",
        "Too hot to function, too stubborn to stay inside",
        "This weather is brought to you by the seventh circle of Hell",
        "I'm basically a walking puddle of regret right now",
        "It's so hot, my car's AC threw up its hands and quit",
        "This is hotter than gas station sushi left in the sun",
        "Weather update: We're all slowly becoming jerky",
        "It's like someone turned Earth's difficulty setting to 'Australian Summer'",
        "Today's vibe: spontaneous human barbecue",
        "This heat is more aggressive than a used car salesman",
        "I'm not sweating, I'm leaking awesome sauce (it's sweat)",
        "Someone cranked the thermostat to 'Mordor'",
        "It's so hot, I just saw the devil buying sunscreen",
        "This weather is faker than my enthusiasm for small talk",
        "Hottest day since... yesterday? Climate's wild, yo",
        "Perfect temperature for cooking eggs on the sidewalk and your dreams",
        "This is why aliens won't visit us",
        "It's so hot, I'm considering moving to the Arctic just for the vibes",
        "Today's forecast: Surface of the sun with light regret",
        "This heat is testing my will to live more than Monday mornings",
        "I'm literally becoming one with the asphalt",
        "It's hotter than a stolen tamale",
        "This weather is what happens when God gets hangry",
        "If Hell had a weather report, it'd be more pleasant than this",
        "I'm sweating in places I didn't know could sweat",
        "This is what dying stars feel like, probably",
        "Someone pressed the 'microwave Earth' button",
        "It's so hot, even vampires are getting sunburned",
        "This heat has more attitude than a hormonal teenager",
        "Weather brought to you by: Regret™",
        "I didn't know we were auditioning for Mad Max today",
        "This is hotter than my mixtape (and that's saying something)",
        "The sun woke up and chose violence today",
        "It's so hot, my ice cream surrendered before I could eat it",
        "Today's temperature: One degree below 'nope'",
        "This weather is more aggressive than my cat at 3 AM",
        "I'm not built for this kind of atmospheric betrayal",
        "It's like being in a hair dryer set to 'punishment'",
        "This heat is the universe's way of saying 'stay inside, dummy'",
        "Weather forecast: Hell's sauna with scattered crying",
        "I've given up on life and embraced my fate as a puddle",
        "This is what happens when Mercury is in Gatorade",
        "It's so hot, I just saw a cactus asking for water",
        "Today's brought to you by climate chaos and bad decisions",
        "This weather is faker than reality TV",
        "I'm melting faster than the Wicked Witch",
        "It's hotter than a habanero in a sauna",
        "This is God's way of saying 'I'm not mad, just disappointed'",
        "Weather update: Absolute hellfire with a side of misery",
        "I didn't ask to be microwaved today, but here we are",
        "This heat is more toxic than my ex",
        "It's like being trapped in an air fryer",
        "Today's vibe: Crispy on the outside, dead on the inside",
        "This is hotter than a server room in August",
        "I'm convinced the sun has beef with humanity",
        "Weather forecast: Regrettable with a chance of nope",
        "It's so hot, even my will to live is evaporating",
        "This is what happens when you anger the weather gods",
        "I'm basically a rotisserie chicken at this point",
        "This heat is more aggressive than a goose protecting its nest",
        "Today's forecast: Too damn hot to exist",
        "It's like standing in front of a jet engine made of rage",
        "This weather is brought to you by poor life choices",
        "I'm sweating in dimensions science hasn't discovered yet",
        "It's so hot, even Hell sent a sympathy card",
        "This is hotter than the drama in my group chat",
        "Weather update: Big oof energy all day",
        "I didn't know we were cosplaying as bacon today",
        "This heat has more intensity than my caffeine addiction",
        "It's like someone weaponized summer",
        "Today's brought to you by the apocalypse starter pack",
        "This weather is what happens when karma gets creative",
        "I'm not saying it's hot, but I just saw ice spontaneously apologizing",
        "This is hotter than my phone after 5% battery life",
        "Weather forecast: Satan's exhale with scattered regrets",
        "It's so hot, I'm considering filing a complaint with God",
        "This heat is more dramatic than a soap opera season finale"
      ],
      partlySunny: [
        "The sun is social distancing today.",
        "It's like the sky can't make up its mind. Relatable.",
        "Oh, look, a cloud. Groundbreaking.",
        "Partly sunny? More like partly disappointing.",
        "The sun is being shy. Or it's just avoiding you.",
        "It's 'I might need sunglasses, I might not' weather. Annoying.",
        "The sky is throwing shade. Literally.",
        "Not sunny. Not cloudy. Just... indecisive.",
        "The sun is here, it's just not committing.",
        "Looks like the sun hit the snooze button.",
        "Partly sunny. Fully 'meh'.",
        "Weather forecast: 50% chance of a good mood.",
        "It's like the sky is gaslighting us.",
        "A few clouds, just to keep you on your toes.",
        "The sun's trying, I guess. We'll give it a C+."
      ],
      cloudy: [
        "The sun has left the chat.",
        "It's gray. Just... gray. Like my soul.",
        "The sky is currently buffering.",
        "Weather forecast: 50 shades of blah.",
        "Looks like the sun called in sick today.",
        "The sky is ghosting us.",
        "Oh good. A ceiling of depression.",
        "Today's vibe: emotionally overcast.",
        "This weather is as exciting as a plain rice cake.",
        "The sun is cancelled.",
        "It's not 'dark,' it's 'atmospherically challenged'.",
        "If this weather had a flavor, it would be 'tap water'.",
        "The sky's emo phase is really lasting a while.",
        "Congrats, the sun has been blocked.",
        "It's colder than a witch's tit in a brass bra",
        "Holy shivers Batman, bundle the hell up",
        "Freezing my ass off isn't just an expression anymore",
        "It's so cold, my attitude has frozen",
        "Winter said 'hold my beer' and cranked it to arctic",
        "This cold is more aggressive than my ex's lawyer",
        "It's colder than your ex's heart out there",
        "Mother Nature really woke up and chose hypothermia",
        "I didn't sign up for this ice age revival",
        "It's so cold, I just saw a polar bear wearing a parka",
        "This is what happens when Elsa gets pissed",
        "Winter is coming? Nah, winter's already here kicking ass",
        "It's colder than a penguin's nightmare",
        "Someone forgot to pay the heating bill for Earth",
        "This cold has more bite than a rabid chihuahua",
        "I'm basically a human popsicle now",
        "It's so cold, my coffee froze mid-sip",
        "Today's vibe: frozen disappointment",
        "This is colder than the comments section on a controversial post",
        "Winter came early and brought all its baggage",
        "It's like living in a walk-in freezer",
        "I've given up feeling in my extremities",
        "This cold is brought to you by questionable life choices",
        "It's so cold, even the sun called in sick",
        "Weather forecast: Frostbite with scattered regrets",
        "I'm not built for this kind of arctic nonsense",
        "This is what dying in slow motion feels like",
        "It's colder than a snowman's balls",
        "Today's sponsored by hypothermia and bad decisions",
        "I'm basically a frozen chicken nugget at this point",
        "This cold has more attitude than a teenager",
        "It's so cold, my tears froze before they could fall",
        "Winter said 'let me show you some real cold' and delivered",
        "This is colder than my landlord's email responses",
        "I didn't know we were auditioning for The Day After Tomorrow",
        "It's like someone set the thermostat to 'screw you'",
        "This cold is testing my will to exist",
        "Weather update: Ice age with scattered crying",
        "I'm convinced winter has personal beef with me",
        "It's so cold, even penguins are asking what's wrong",
        "This is what happens when God forgets to pay the heating bill",
        "Today's brought to you by frozen misery",
        "I'm not saying it's cold, but I just saw the sun shivering",
        "This cold is more intense than my coffee addiction withdrawal",
        "It's like being trapped in a meat locker",
        "Weather forecast: Arctic hellscape all week",
        "I've accepted my fate as a human icicle",
        "This is colder than a snowman's revenge",
        "It's so cold, my breath is making snow angels",
        "Today's vibe: Jack Frost being a dick",
        "This cold is more aggressive than geese in a park",
        "I'm basically losing circulation in all my appendages",
        "It's like winter looked at the calendar and said 'nah'",
        "This is what happens when you piss off Elsa",
        "Weather update: Colder than your ex's goodbye text",
        "I didn't ask to cosplay as a frozen burrito today",
        "This cold has more edge than an emo band from 2007",
        "It's so cold, even my shadow abandoned me",
        "Today's forecast: Frostbite city, population: everyone",
        "This is colder than the reception at a family reunion",
        "I'm sweating... wait no, that's just ice forming on my face",
        "It's like someone turned Earth into a giant freezer",
        "This cold is brought to you by poor planning and hubris",
        "Weather forecast: Frozen wasteland with light suffering",
        "I'm not built for this Antarctic bullshit",
        "It's so cold, I just saw hell freezing over in real-time",
        "This is what happens when winter gets its feelings hurt",
        "Today's sponsored by frozen regret",
        "I'm basically an ice sculpture at this point",
        "This cold is more dramatic than a reality TV show",
        "It's like being slapped by winter repeatedly",
        "Weather update: Freezer burn for everyone",
        "I've given up on being warm ever again",
        "This is colder than my boss's sense of humor",
        "It's so cold, my phone's battery gave up",
        "Today's vibe: Arctic apocalypse",
        "This cold has more intensity than my existential dread",
        "I'm not saying it's cold, but I just saw ice fishing itself",
        "It's like winter declared war on humanity",
        "This is what happens when climate gets creative with suffering",
        "Weather forecast: Frozen hell with scattered complaints",
        "I didn't know we were filming The Thing today",
        "This cold is more toxic than online discourse",
        "It's so cold, even my car refused to start out of principle",
        "Today's brought to you by winter's greatest hits",
        "I'm basically transforming into a frozen pizza",
        "This is colder than a sociopath's bedside manner",
        "It's like someone weaponized winter",
        "Weather update: Ice age 2: Electric Boogaloo",
        "I'm convinced the thermostat is stuck on 'Arctic death'",
        "This cold is more aggressive than a Canadian goose",
        "It's so cold, I just saw frostbite applying for a job",
        "Today's forecast: Frozen disappointment all around",
        "This is what happens when winter takes steroids",
        "I've accepted that warmth is just a myth",
        "It's like being trapped in Hoth without a tauntaun",
        "This cold is brought to you by nature's cruelty",
        "Weather forecast: Sub-zero suffering with scattered ice",
        "I'm not built for this kind of frozen betrayal"
      ],
      rain: [
        "Mother Nature's having a good cry today",
        "Somebody pissed off the sky again",
        "Rain rain, go the fuck away, nobody invited you to stay",
        "The sky is leaking more than my motivation",
        "It's wetter than... well, use your imagination",
        "Perfect weather for staying in bed and ignoring responsibilities",
        "The clouds are having a breakdown and making it our problem",
        "It's raining harder than my student loan payments",
        "Sky's crying more than me watching The Notebook",
        "Someone forgot to turn off the celestial faucet",
        "This rain has more commitment than my last relationship",
        "Weather brought to you by tears and regret",
        "It's so wet, even the ducks are complaining",
        "Today's forecast: Soggy disappointment",
        "The sky woke up and chose emotional damage",
        "It's raining cats, dogs, and poor life choices",
        "This weather is faker than my enthusiasm for small talk",
        "Perfect day to question all your life decisions indoors",
        "The universe is literally crying on us",
        "It's wetter than a water park designed by sadists",
        "Rain check? More like rain wreck",
        "This precipitation has more attitude than a teenager",
        "Weather update: Liquid sadness falling from sky",
        "I didn't sign up for this aquatic nightmare",
        "It's raining harder than my anxiety on Sundays",
        "The sky's having a moment and we're all suffering",
        "This rain is more dramatic than a soap opera",
        "Perfect weather for contemplating poor decisions",
        "It's so rainy, even fish are looking for umbrellas",
        "Today's sponsored by wet socks and regret",
        "The clouds are stress-releasing on everyone",
        "It's raining more than a sad movie marathon",
        "Weather forecast: Soggy misery with scattered puddles",
        "This rain has more persistence than my student loans",
        "I'm convinced the sky is trolling us",
        "It's wetter than a failed waterpark inspection",
        "Today's vibe: Drowned rat aesthetic",
        "The sky is having an existential crisis",
        "It's raining harder than my credit card bills",
        "This weather is brought to you by chaos and water",
        "Perfect day to stay inside and hate everything",
        "The clouds are having a full meltdown",
        "It's so wet, even umbrellas are surrendering",
        "Weather update: Sky tears with scattered depression",
        "I didn't ask to be baptized today but here we are",
        "This rain is more aggressive than my alarm clock",
        "It's like someone weaponized clouds",
        "Today's forecast: Liquid disappointment everywhere",
        "The sky decided violence was the answer",
        "It's raining harder than my existential dread",
        "This weather is what happens when clouds get hangry",
        "Perfect conditions for regretting your commute",
        "It's so rainy, I'm growing webbed feet",
        "Today's sponsored by puddles and poor planning",
        "The universe is crying harder than my bank account",
        "It's wetter than a pool party gone wrong",
        "Weather forecast: Aquatic apocalypse all day",
        "This rain has more drama than my group chat",
        "I'm basically becoming a fish at this point",
        "It's like the sky opened a faucet of suffering",
        "Today's brought to you by waterproof regrets",
        "The clouds are having a breakdown on our behalf",
        "It's raining more than my unpaid bills",
        "This weather is faker than my work smile",
        "Perfect day for contemplating life's failures",
        "It's so wet, even boats are confused",
        "Weather update: Soggy chaos with scattered tears",
        "I didn't know we were auditioning for Waterworld",
        "This rain is more intense than my caffeine withdrawal",
        "It's like someone turned on all the sky faucets",
        "Today's vibe: Perpetually damp disappointment",
        "The sky's crying harder than me at the DMV",
        "It's raining enough to make Noah nervous",
        "This weather is brought to you by wet socks inc.",
        "Perfect conditions for indoor existential dread",
        "It's so rainy, I'm considering building an ark",
        "Weather forecast: Liquid misery with scattered regret",
        "This rain has more commitment than most relationships",
        "I'm basically a human sponge now",
        "It's like the clouds are having a group therapy session",
        "Today's sponsored by soggy shoes and sadness",
        "The sky is leaking faster than my savings account",
        "It's wetter than a poorly planned pool party",
        "Weather update: Biblical flood vibes",
        "I didn't sign up for this aquatic betrayal",
        "This rain is more persistent than spam calls",
        "It's so wet, even fish are building shelters",
        "Today's forecast: Precipitation with attitude",
        "The universe decided we all need showers apparently",
        "It's raining harder than my Monday morning dread",
        "This weather is what happens when clouds get petty",
        "Perfect day to stay dry and bitter indoors",
        "It's like someone broke the sky's plumbing",
        "Weather forecast: Wet chaos everywhere",
        "I'm convinced the rain has personal beef with everyone",
        "This precipitation is more aggressive than rush hour traffic",
        "It's so rainy, I'm considering evolving gills",
        "Today's brought to you by dampness and disappointment",
        "The clouds are crying more than a telenovela character",
        "It's wetter than a broken fire hydrant"
      ],
      thunderstorm: [
        "The sky is having a full-blown tantrum.",
        "Zeus is angry. Or Thor. Someone's angry.",
        "Weather forecast: Loud noises and wetness. Stay inside.",
        "It's God's own light show. Don't get zapped.",
        "If you go outside, you're a moron. Just saying.",
        "The sky is angry. I'd hide if I were you.",
        "Today's vibe: 'Final Boss Battle'.",
        "This is not 'walk the dog' weather. This is 'cower' weather.",
        "Ooh, spicy rain!",
        "The clouds are fighting. Don't get in the middle of it.",
        "Nature's reminding you that it can, in fact, kill you.",
        "Free light show! With a chance of electrocution.",
        "It's like a rave, but angry and wet.",
        "This is your sign to binge-watch something.",
        "The weather is very, very, not calm."
      ],
      snow: [
        "It's snowing! Time to drive like you've never seen a road before",
        "Winter wonderland or frozen hellscape? You decide",
        "Snow days are only fun when you're not the one shoveling",
        "Perfect weather for staying inside and judging people who like winter",
        "It's snowing, which means everyone forgot how to drive",
        "Winter is pretty until you have to exist in it",
        "Snow: Nature's way of saying 'stay home'",
        "It's a winter wonderland of regret and cold toes",
        "Perfect day for hot cocoa and existential dread",
        "Snow is just frozen rain with better PR",
        "Today's forecast: White fluffy bullshit everywhere",
        "It's snowing, time for everyone to panic buy bread and milk",
        "Winter showed up uninvited and brought all its baggage",
        "Perfect weather for questioning your life choices",
        "Snow: Pretty to look at, hell to deal with",
        "Today's brought to you by frozen precipitation and regret",
        "It's snowing, which means your commute just tripled",
        "Winter wonderland? More like winter nightmare",
        "Perfect day to hibernate like a sane creature",
        "Snow is nature's glitter: looks nice, gets everywhere, impossible to remove",
        "Today's vibe: Frozen inconvenience",
        "It's snowing, time to rediscover your hatred of winter",
        "Perfect weather for indoor sulking",
        "Snow: Because regular rain wasn't annoying enough",
        "Today's forecast: Frozen chaos with scattered accidents",
        "It's a white Christmas or white hell, depending on your perspective",
        "Perfect day to appreciate central heating",
        "Snow is pretty for exactly 5 minutes, then it's just work",
        "Today's brought to you by frozen water and poor timing",
        "It's snowing, which means half the city can't function",
        "Winter is just nature's way of being passive-aggressive",
        "Perfect weather for regretting living where you live",
        "Snow: Instagram worthy, life ruining",
        "Today's vibe: Frozen frustration",
        "It's snowing, time to remember you hate driving in this",
        "Perfect day for staying inside and being bitter",
        "Snow is nature's way of saying 'good luck with that'",
        "Today's forecast: White frozen nonsense",
        "It's a winter wonderland until you have to go anywhere",
        "Perfect weather for hating winter sports enthusiasts",
        "Snow: Pretty in photos, hell in practice",
        "Today's brought to you by frozen inconvenience",
        "It's snowing, which means logic goes out the window",
        "Winter showed up like that friend who doesn't know when to leave",
        "Perfect day to appreciate heated blankets",
        "Snow is just water having a midlife crisis",
        "Today's vibe: Frozen annoyance",
        "It's snowing, time for seasonal depression to kick in",
        "Perfect weather for indoor hibernation",
        "Snow: Nature's most beautiful inconvenience"
      ],
      general: [
        "Weather exists, and you have to deal with it",
        "It's a day, with weather happening",
        "Mother Nature is feeling... something today",
        "Another day, another weather situation",
        "The sky is doing sky things",
        "Weather: It's happening whether you like it or not",
        "Today's forecast: Existing outside is required",
        "It's the kind of day that makes you think thoughts",
        "Weather brought to you by atmospheric conditions",
        "The universe is being weather-like today",
        "It's a whole vibe out there, interpret as you will",
        "Today's weather: Definitely happening",
        "The atmosphere is atmosphering pretty hard today",
        "Weather forecast: Yep, it's weather alright",
        "Another day of Earth doing Earth things",
        "Today's brought to you by climate and consequences",
        "The weather gods are feeling... present",
        "It's the kind of day that makes you feel ways about stuff",
        "Weather: Still a thing that happens",
        "Today's vibe: Existing in the atmosphere",
        "The sky is having a day",
        "Weather forecast: Atmospheric conditions apply",
        "It's weather, what more do you want from me?",
        "Today's brought to you by meteorology and mild chaos",
        "The weather is weathering",
        "Another day, another atmospheric situation",
        "It's the kind of day that makes you consider things",
        "Weather: Happening as we speak",
        "Today's forecast: Outside conditions vary",
        "The universe is doing its usual weather shenanigans",
        "It's a day that exists, and so does weather",
        "Weather brought to you by physics and atmospheric pressure",
        "Today's vibe: Weather is occurring",
        "The sky is being particularly sky-like today",
        "Weather forecast: Yes",
        "It's the kind of day that happens sometimes",
        "Today's brought to you by climate patterns",
        "The atmosphere is atmosphering adequately",
        "Weather: Still doing its thing",
        "Today's forecast: Conditions are conditional",
        "It's weather, and it's happening to everyone",
        "The universe is feeling weather-y today",
        "Another day of atmospheric shenanigans",
        "Weather brought to you by the sky's mood",
        "Today's vibe: Weather-adjacent",
        "It's the kind of day that makes you think 'hmm, weather'",
        "Weather forecast: Atmospheric vibes",
        "The sky is doing what skies do",
        "Today's brought to you by meteorological conditions",
        "Weather: A thing that's happening"
      ]
    },
    // Theme-specific SASSY phrases
    themes: {
      naval: {
        sunny: ["If you're not on a boat right now, what's the point?", "This is what they call 'perfect sailing weather,' landlubber."],
        rain: ["A real sailor isn't afraid of a little spray. Get out there.", "It's just wind, you coward. It's called 'sailing'."],
        thunderstorm: ["This is it. The perfect storm. Don't be a hero."],
        general: ["Stop being a landlubber."]
      },
      sunset: {
        sunny: ["The sky is showing off. You should be watching.", "Weather's better than your Instagram filter. Go look."],
        cloudy: ["Of course it's cloudy. The sky hates you.", "A grey, dull, disappointing sunset. How fitting."],
        general: ["At least the sky is trying."]
      },
      neon: {
        sunny: ["Perfect night to light it up. Don't stay home.", "The city is calling. Don't let it go to voicemail."],
        rain: ["Rain's making the neon blur. Just like your vision will be later."],
        thunderstorm: ["The city's electric, and so is the sky! Don't get zapped."],
        general: ["Go be the main character in your cyberpunk movie."]
      },
      arctic: {
        sunny: ["It's not 'actively trying to kill you' cold. That's a win.", "A 'balmy' 30 degrees. Put on a t-shirt."],
        snow: ["It's cold. Again. What did you expect?", "Another blizzard. Hope you like the inside of your house."],
        general: ["Yes, it's freezing. Complaining won't make it warmer."]
      },
      highseas: {
        sunny: ["The sea is calm. Too calm...", "Perfect day to pretend you're a pirate."],
        rain: ["It's raining. The ocean is wet. You'll survive."],
        thunderstorm: ["Poseidon is angry. Stay off the water, idiot."],
        general: ["Stop being a scallywag and check the forecast."]
      },
      aurora: {
        sunny: ["The sky is clear. Look up, you might see something cool.", "Stop looking at your screen and look at the *actual* sky."],
        cloudy: ["Too cloudy. The universe said 'not today'.", "No aurora for you. Go to bed."],
        general: ["Look up, or don't. I don't care."]
      },
      arcane: {
        sunny: ["The vibes are immaculate. Go manifest something.", "This weather feels magical. Don't waste it."],
        cloudy: ["The fog is thick. Perfect for disappearing."],
        rain: ["This gloomy weather is perfect for summoning... a pizza."],
        thunderstorm: ["The sky is casting 'Lightning Bolt'. I'd take cover."],
        general: ["The spirits are... feeling a type of way."]
      },
      solstice: {
        sunny: ["It's the longest day of the year. You have no excuse for being lazy.", "Maximum sunshine. Go absorb some."],
        cloudy: ["Cloudy. The sun took the day off. On its own day.", "The sun is failing at its one job."],
        general: ["Praise the sun! Or whatever."]
      },
      evergreen: {
        sunny: ["Go smell a tree. It's nice out.", "The forest is perfect. Go get lost in it. (Don't actually)."],
        rain: ["It's raining. The forest is now a mud pit. Have fun."],
        cloudy: ["Bigfoot weather. Stay inside."],
        general: ["Go touch some moss, you nerd."]
      },
      voyager: {
        sunny: ["Engage! Go explore... the backyard, at least.", "Atmosphere is stable. You are cleared for outdoor activity."],
        rain: ["Atmospheric interference. Abort mission."],
        thunderstorm: ["Warning: Energy discharge detected. Shields up!"],
        general: ["Make it so... or don't."]
      },
      monochrome: {
        sunny: ["It's sunny. In black and white, it would just be 'bright'."],
        cloudy: ["It's grey. How appropriate for your theme.", "The weather is as uninspired as this theme."],
        rain: ["Rainy, cold, and grey. A perfect mood."],
        general: ["It's... weather."]
      },
      playful: {
        sunny: ["It's a 'slide whistle' kind of day. Go be annoying outside.", "This weather is more fun than a ball pit."],
        rain: ["Rain. The outside is cancelled. Play-Doh time."],
        cloudy: ["This weather is a big, sad, grey frowny face."],
        general: ["Go play! Or don't. See if I care."]
      },
      retro90: {
        sunny: ["It's da bomb out. Stop being a scrub and go outside.", "This weather is fresh. Don't be a dweeb, get off the couch."],
        rain: ["This rain is wack. Stay inside.", "It's raining? Whatever. Talk to the hand."],
        general: ["As if!"]
      },
      groove70: {
        sunny: ["This weather is dy-no-mite! Go be cool.", "It's a stone cold groove out there."],
        rain: ["This rain is a real buzzkill.", "Don't be a jive turkey, stay inside."],
        general: ["Catch you on the flip side."]
      },
      mojave: {
        sunny: ["It's hot. What, you expected snow?", "Dry, hot, and sunny. It's the desert. Duh."],
        rain: ["It's raining. In the desert. Go buy a lottery ticket."],
        general: ["It's the desert. It's dry. Shocking."]
      },
      atomic50: {
        sunny: ["What a swell day! Go put on some slacks.", "The weather is just peachy keen."],
        rain: ["Heavens to Betsy, this rain won't quit."],
        cloudy: ["Gee whiz, it's a bit gray out."],
        general: ["Don't be a square."]
      },
      psychedelic60: {
        sunny: ["The vibes are just... cosmic, man.", "Go tune in, turn on, and drop... into a park or something."],
        rain: ["This rain is a bad trip. Stay inside."],
        general: ["Heavy, man. Just heavy."]
      },
      arcade80: {
        sunny: ["The weather is, like, totally awesome to the max.", "No way! This weather is choice."],
        rain: ["This rain is, like, grody. Gag me."],
        snow: ["It's bogus cold. Stay home and play Pac-Man."],
        general: ["This weather is a total bummer."]
      },
      y2k00: {
        sunny: ["This weather is phat. Go download some sun.", "It's a sweet day to hang with your peeps."],
        rain: ["This rain is not the download I wanted.", "This weather is a 404 error."],
        general: ["Word up."]
      },
      metro10: {
        sunny: ["This weather is #blessed. Go get that content.", "It's a good day to be the main character."],
        cloudy: ["This weather is not the vibe."],
        rain: ["It's raining. I can't even. Literally."],
        general: ["It is what it is."]
      },
      sushi: {
        sunny: ["A crisp, clean, perfect day.", "The weather is as fresh as high-grade tuna."],
        rain: ["This rain is messy. No elegance.", "A bit wet. Good day for some warm sake."],
        general: ["A day of perfect balance. Or not."]
      },
      bbq: {
        sunny: [
          "Bitch, it is too nice not to grill.",
          "Get your tongs, loser, we're grilling.",
          "If you're not grilling in this weather, you're dead inside.",
          "This is prime-time, top-tier, A+ grilling weather. Don't screw it up.",
          "The sun's out. If I see you microwaving, we're fighting.",
          "Stop staring at your phone and go stare at a grill.",
          "Weather's perfect. Your excuses for not grilling are not.",
          "Fire up the grill or surrender your 'BBQ Pit' theme privileges.",
          "Hot damn, it's nice. The only smoke should be from a grill.",
          "Stop whatever you're doing. It's grilling time. That's an order."
        ],
        partlySunny: [
          "The sun is half-assing it, but you shouldn't. Grill.",
          "Cloudy, sunny, who cares? The coals are hot.",
          "It's nice enough. Stop debating and start marinating."
        ],
        cloudy: [
          "What, you need the sun to cook? The grill works fine, you baby.",
          "It's cloudy. Good. No sun glaring off your beer can.",
          "A grey day is a great day to make some grey smoke. Fire it up."
        ],
        rain: [
          "Rain? You call that rain? A real griller isn't scared of a little sky-water.",
          "It's cold. So what? Are you a griller or a child?",
          "This is why they invented covered patios, genius.",
          "Let me guess, you're going to order a pizza? Pathetic.",
          "Yeah, it's raining. Your meat's not made of sugar, it won't melt."
        ],
        thunderstorm: [
          "Don't be a dumbass, you can't grill in a lightning storm.",
          "Grilling with metal tongs in a thunderstorm is a 'final destination' move. Don't.",
          "The sky is literally exploding. The ribs can wait."
        ],
        snow: [
          "Snowing? Good. It'll keep your beer cold while you grill.",
          "The grill is hotter than this cold. What's your excuse?",
          "Real pitmasters grill in a blizzard. Don't be weak."
        ],
        general: [
          "Stop looking at this app and go light a fire.",
          "If your first thought wasn't 'I should grill,' you're wrong."
        ]
      },
      cafe: {
        sunny: ["It's too nice for that overpriced latte. Go outside.", "This weather is better than free Wi-Fi."],
        cloudy: ["Perfect weather to overpay for a coffee and look miserable.", "Oh, it's gray. How... 'atmospheric'."],
        rain: ["It's cold. Just like that barista's stare.", "Rainy. Now you have a *real* excuse to be moody in a cafe."],
        general: ["Go drink your bean water, I guess."]
      }
    }
  }
};

/**
 * Maps a weather condition string (from the API) and temperature
 * to one of our defined categories.
 * @param {string} condition - The weather condition string (e.g., "Mainly Clear", "Light Rain")
 * @param {number} temp - The current temperature in Fahrenheit
 * @returns {string} One of ['sunny', 'partlySunny', 'cloudy', 'rain', 'thunderstorm', 'snow', 'general']
 */
function mapConditionToCategory(condition, temp) {
  const conditionLower = (condition || '').toLowerCase();

  if (conditionLower.includes('thunderstorm') || conditionLower.includes('hail')) {
    return 'thunderstorm';
  }
  if (conditionLower.includes('rain') || conditionLower.includes('drizzle') || conditionLower.includes('shower')) {
    return 'rain';
  }
  if (conditionLower.includes('snow') || conditionLower.includes('sleet') || conditionLower.includes('grains')) {
    return 'snow';
  }
  if (conditionLower.includes('fog') || conditionLower.includes('overcast')) {
    return 'cloudy';
  }
  if (conditionLower.includes('partly cloudy')) {
    return 'partlySunny';
  }
  if (conditionLower.includes('clear')) {
    return 'sunny';
  }
  
  // Fallbacks based on temperature if condition is vague
  if (temp > 70) {
    return 'sunny';
  }
  if (temp < 45) {
    return 'cloudy';
  }

  return 'general';
}

/**
 * Get a weather phrase based on temperature, condition, mode, and theme
 * @param {number} temp - Temperature in Fahrenheit
 * @param {string} condition - Weather condition string (e.g., "Partly Cloudy")
 * @param {boolean} isSassy - Whether to use sassy mode
 * @param {string} theme - Current theme name
 * @returns {string} Weather phrase with optional theme flair
 */
export function getWeatherPhrase(temp, condition, isSassy = false, theme = 'naval') {
  const style = isSassy ? 'sassy' : 'regular';
  const category = mapConditionToCategory(condition, temp);
  const phraseDb = weatherSayings[style];
  
  let possiblePhrases = [];

  // 1. Add theme-specific phrases for the exact condition (e.g., sassy.themes.bbq.sunny)
  if (phraseDb.themes[theme] && phraseDb.themes[theme][category]) {
    possiblePhrases.push(...phraseDb.themes[theme][category]);
  }

  // 2. Add general phrases for the exact condition (e.g., sassy.conditions.sunny)
  if (phraseDb.conditions[category]) {
    possiblePhrases.push(...phraseDb.conditions[category]);
  }

  // 3. Fallback: If we have very few specific phrases, add general theme phrases
  if (possiblePhrases.length < 5) {
    if (phraseDb.themes[theme] && phraseDb.themes[theme].general) {
      possiblePhrases.push(...phraseDb.themes[theme].general);
    }
  }
  
  // 4. Fallback: Add general "general" phrases
  if (possiblePhrases.length === 0) {
    possiblePhrases.push(...phraseDb.conditions.general);
  }

  // 5. Ultimate fallback
  if (possiblePhrases.length === 0) {
    possiblePhrases.push(isSassy ? "Weather is happening." : "Have a nice day!");
  }

  // 6. Select random phrase
  const phrase = possiblePhrases[Math.floor(Math.random() * possiblePhrases.length)];
  
  // 7. Add theme-specific flair
  return addThemeFlair(phrase, theme);
}

/**
 * Add theme-specific emoji flair to a phrase
 * @param {string} phrase - The weather phrase
 * @param {string} theme - Current theme name
 * @returns {string} Phrase with theme flair added
 */
function addThemeFlair(phrase, theme) {
	const flair = themeFlairs[theme] || '';
	return flair ? `${flair} ${phrase}` : phrase;
}
